Aqui estão algumas apresentações selecionadas:


### Muito além da técnica: habilidades essenciais para estatísticos (2025)
**Tipo:** Palestra
**Local:** IME-USP
Palestra ministrada para os alunos de graduação em Estatística IME-USP, abordando habilidades interpessoais e comunicação para estudantes da disciplina MAE0413.
[Slides aqui](https://github.com/magnotairone/material/blob/main/Apresenta%C3%A7%C3%A3o%20IME%20USP.pdf).

---

### Introdução à Otimização (2022)
**Tipo:** Workshop  
**Local:** Insper, São Paulo  
Neste workshop, defini o que é um problema de otimização, como modelar um problema e desenvolver soluções para problemas lineares, relacionando otimização com conceitos de aprendizagem estatística.

---

### Noções de SQL, organização e visualização de dados usando o tidyverse (2021)
**Tipo:** Tutorial  
**Local:** Universidade Federal de Santa Maria (Virtual)  
Mini curso apresentado na VII Semana Acadêmica da Estatística da UFSM.

---

### Detecção de pontos de mudança na curva de novos casos de covid-19 (2021)
**Tipo:** Talk  
**Local:** Banco Santander, São Paulo  
Apresentação para o time de marketing analytics do Santander. [Slides aqui](https://rpubs.com/magnotfs/covid19).

---

### Manipulação e organização de bases de dados com dplyr (2021)
**Tipo:** Tutorial  
**Local:** Universidade de São Paulo (Virtual)  
Mini curso apresentado na 5ª edição do Encontro da Pós-graduação em Estatística do IME-USP (EPEI).

---

### Limpeza e organização de bases de dados (2021)
**Tipo:** Workshop  
**Local:** Insper, São Paulo  
Discussão sobre formatos de dados, convenções de armazenamento e práticas essenciais para limpeza e organização de dados.

---

### Estimation and model selection for mixing graphical models (2021)
**Tipo:** Talk  
**Local:** 63rd ISI World Statistics Congress (Virtual)  
Apresentação de parte da pesquisa do doutorado. Talk pré-gravado para o ISI 2021.

---

### Independent block identification in multivariate time series (2020)
**Tipo:** Talk  
**Local:** Bernoulli-IMS One World Symposium (Virtual)  
Talk pré-gravado para o Bernoulli-IMS One World Symposium 2020.

---

### Prêmio Vídeo Pós-Graduação no combate ao COVID-19 (2020)
**Tipo:** Prêmio  
Premiação pelo vídeo de divulgação do projeto sobre análise de dados da Covid-19, concedido pela Pró-Reitoria de Pós-Graduação da USP.