### Artigos Científicos Publicados em Periódicos

* [Model selection for Markov random fields on graphs under a mixing condition](https://www.sciencedirect.com/science/article/abs/pii/S030441492400231X)
**Stochastic Processes and their Applications**
<br><small>M. T. F. Severino & Florencia Leonardi, 2025.</small>

* [Independent block identification in multivariate time series](https://onlinelibrary.wiley.com/doi/abs/10.1111/jtsa.12553)
**Journal of Time Series Analysis (2021)**
<br><small>Florencia Leonardi, Matías Lopez-Rosenfeld, Daniela Rodriguez, Magno T. F. Severino, Mariela Sued, 2021.</small>

### Artigos Científicos não Publicados

* [Model selection criteria for regression models with splines and the automatic localization of knots](https://arxiv.org/abs/2006.02649). <small>Sousa, A.R., Severino, M. T. F., and Leonardi, F. </small>, 2020.

### Outras publicações

* Tese de Doutorado (IME-USP): [Estimation and model selection for graphical models](https://www.teses.usp.br/teses/disponiveis/45/45133/tde-25042024-181144/pt-br.php), 2024.

* Dissertação de Mestrado (DEST-UFMG): [Extending JAGS for spatial data](https://repositorio.ufmg.br/items/cf35e8cb-4e1d-434f-a02b-2fb45d2b4cdc), 2018.

### Software

* [**GeoJAGS**](https://sourceforge.net/projects/geojags/files/) (Módulo C++ / JAGS)

* [**MixingGraph**](https://github.com/magnotairone/MixingGraph) (Pacote R)
